# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1033, 610)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_1.setGeometry(QtCore.QRect(220, 2, 31, 20))
        self.lineEdit_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.but_matr = QtWidgets.QPushButton(self.centralwidget)
        self.but_matr.setGeometry(QtCore.QRect(260, 0, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.but_matr.setFont(font)
        self.but_matr.setObjectName("but_matr")
        self.but_close_4 = QtWidgets.QPushButton(self.centralwidget)
        self.but_close_4.setGeometry(QtCore.QRect(390, 0, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.but_close_4.setFont(font)
        self.but_close_4.setObjectName("but_close_4")
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setGeometry(QtCore.QRect(0, 20, 1031, 541))
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1033, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Лабораторная работа #2"))
        self.label.setText(_translate("MainWindow", "Размерность матрицы (от 1 до 10):"))
        self.lineEdit_1.setText(_translate("MainWindow", "3"))
        self.but_matr.setText(_translate("MainWindow", "Обновить матрицу"))
        self.but_close_4.setText(_translate("MainWindow", "Пересчитать"))
